name: Atualizar README com estatísticas privadas

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Atualizar estatísticas
        uses: anuraghazra/github-readme-stats@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
