name: Atualizar README com estatísticas privadas

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar estatísticas e atualizar README
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=adrianoreidel&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true"
          curl -o github-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=adrianoreidel&theme=tokyonight&layout=compact&custom_title=Tecnologias&langs_count=9"

      - name: Configurar credenciais do Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adrianoreidel/adrianoreidel.git

      - name: Commit e push das atualizações
        run: |
          git add github-stats.svg github-langs.svg
          git commit -m "Atualizar estatísticas do GitHub no README" || echo "Nenhuma mudança para commit"
          git push
